---
title: "Mellone"
author: "Bruno Mellone"
format: html
---

```{r}
library(here)
library(dplyr)
library(ggplot2)
library(tidyr)
library(vroom)
library(readr)
here :: i_am("lab-grades.Rproj")
```
# 1.1 Study organization
Question 1
```{r}
courses <- vroom(here("data","courses.csv"))
```
Question 2
```{r}
courses |>
  arrange(course) |>
  rename(
    `course name`    = course,
    identifier       = course_id,
    module           = module,
    `number of exams` = nb_grades
  ) |>
  knitr::kable()
```


# 1.2 Students

Question 3
```{r}
students <- vroom(here("data","students.csv"))
cols(
  id = col_double(),
  group = col_double(),
  birth_date = col_date(format = ""),
  sex = col_character(),
  .delim = ","
)
```
```{r}
students <- vroom(
  here("data", "students.csv"),
  col_types = cols(
    id = col_double(),
    group = col_double(),
    birth_date = col_date(), 
    sex = col_factor()       
  )
)
```


# 1.3 Grades
Question 4

```{r}
grades <- read_delim(here("data", "grades.csv"),
  delim = ";",
  na = "unknown")
```

# 2 Student population analysis

Question 5

```{r}
students |>
  summarise(n = n(), .by = group) |>
  ggplot(aes(x = group, y = n)) +
  geom_col() +
  labs(x = "group", y = "number of students")
```

Question 6
```{r}
students |>
  summarise(n = n(), .by = c(group, sex)) |>
  ggplot(aes(x = group, y = n, fill = sex)) +
  geom_col(position = "fill") +
  labs(x = "group", y = "proportion of students", fill = "sex")

```




